spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:// 10.203.156.100:3306/chatdb?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: "06280801"

  thymeleaf:
    cache: false

mybatis:
  type-aliases-package: com.net.chatroom.model.po
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /